### ISSUE TITLE
support hypercores

### ISSUE THREAD

**Issue by yoshuawuyts** [karissa/hyperhealth#2]
It'd be cool if this also supported `hypercore` as we could then plug it into our `hyperops` tools

**Comment by okdistribute** [comment]
```
var memdb = require('memdb')
var hyperdrive = require('hyperdrive')
var hyperhealth = require('hyperhealth')

var db = memdb()
var drive = hyperdrive(db)
var key = '503cf9e12d8ae49a07568d90f04bbdbfa3f1998ab97ed2b5143c1f3f69ec052f'
var archive = drive.createArchive(key, {sparse: true, live: true})
var health = hyperhealth(archive)
```

gives
```
Error: Unknown message type: unknown
    at getEncoding (/Users/karissa/node_modules/dat.land/node_modules/hyperdrive-encoding/index.js:24:19)
    at Object.decode (/Users/karissa/node_modules/dat.land/node_modules/hyperdrive-encoding/index.js:32:13)
    at /Users/karissa/node_modules/dat.land/node_modules/hyperdrive/archive.js:524:30
    at done (/Users/karissa/node_modules/dat.land/node_modules/hypercore/lib/feed.js:190:5)
    at /Users/karissa/node_modules/dat.land/node_modules/levelup/lib/levelup.js:230:7
    at Immediate.callNext (/Users/karissa/node_modules/dat.land/node_modules/memdown/memdown.js:173:5)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by joehand** [comment]
Updated https://github.com/joehand/drive-or-core to be actually helpful! 

It's still a bit hard because you have to create the feed first. But you can then create an archive from that. I can take a shot at this next week unless someone is interested in jumping on it.

**Comment by joehand** [comment]
Done in #5.

CLI only supports archives right now but thats okay I think.
